version: '3.9'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./data:/opt/keycloak/data/import
    command: start-dev --import-realm